In [ ]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 7.마케팅정보

In [ ]:
import pandas as pd

# 1. 사용할 월 리스트
months = ['07', '08', '09', '10', '11', '12']

# 2. 파일 경로 리스트 생성
base_path = '/content/drive/MyDrive/11_파이널프로젝트관련/open/train/7.마케팅정보/'
file_list = [f'{base_path}2018{month}_train_마케팅정보.parquet' for month in months]

# 3. parquet 파일 읽어서 병합
df_list = [pd.read_parquet(file) for file in file_list]
merged_df = pd.concat(df_list, ignore_index=True)

# 4. 결과 확인
merged_df

,기준년월,ID,컨택건수_카드론_TM_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_CA_TM_B0M,컨택건수_이용유도_TM_B0M,컨택건수_신용발급_TM_B0M,컨택건수_부대서비스_TM_B0M,컨택건수_포인트소진_TM_B0M,컨택건수_보험_TM_B0M,...,컨택건수_카드론_당사앱_R6M,컨택건수_CA_당사앱_R6M,컨택건수_리볼빙_당사앱_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_FDS_B0M,컨택건수_채권_R6M,컨택건수_FDS_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M
0,201807,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1,201807,TRAIN_000001,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15회 이상,10일 이상
2,201807,TRAIN_000002,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
3,201807,TRAIN_000003,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
4,201807,TRAIN_000004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399996,201812,TRAIN_399996,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,20회 이상,15일 이상
2399997,201812,TRAIN_399997,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399998,201812,TRAIN_399998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399999,201812,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상

In [ ]:
# merged_df.to_parquet('2018_train_마케팅정보.parquet', index=False)
# print("병합되었습니다 !")

병합되었습니다 !

In [ ]:
import pandas as pd

# 1. 파일 읽기

df1 = pd.read_parquet('/content/drive/MyDrive/11_파이널프로젝트관련/open/train/1.회원정보/ID_Segment.parquet')
df2 = pd.read_parquet('/content/2018_train_마케팅정보.parquet')

# 2. ID 기준으로 병합
merged_df = pd.merge(df1, df2, on='ID', how='inner')  # 또는 how='outer', 'left', 'right'

print(merged_df.shape)           # (약 2400000, 약 106) 예상
print(len(merged_df.columns))    # 약 106개 예상
print(merged_df.columns[:10])

merged_df.to_parquet('마케팅정보_세그먼트병합.parquet', index=False)
print("병합되었습니다 !")

In [ ]:
# 데이터 프레임 정보 확인
merged_df = pd.read_parquet('/content/마케팅정보_세그먼트병합.parquet')

# 생략 없이 컬럼 전체 다 보이게 설정
pd.set_option('display.max_columns', None)    # 모든 컬럼 다 보기
pd.set_option('display.max_rows', None)       # 모든 행 보기 (주의: 너무 크면 과부하)
pd.set_option('display.max_colwidth', None)   # 컬럼 안 내용 생략 없이 보기

# 그리고 나서 출력
merged_df.dtypes

ID                   object
Segment              object
기준년월                  int64
컨택건수_카드론_TM_B0M       int64
컨택건수_리볼빙_TM_B0M       int64
컨택건수_CA_TM_B0M        int64
컨택건수_이용유도_TM_B0M      int64
컨택건수_신용발급_TM_B0M      int64
컨택건수_부대서비스_TM_B0M     int64
컨택건수_포인트소진_TM_B0M     int64
컨택건수_보험_TM_B0M        int64
컨택건수_카드론_LMS_B0M      int64
컨택건수_CA_LMS_B0M       int64
컨택건수_리볼빙_LMS_B0M      int64
컨택건수_이용유도_LMS_B0M     int64
컨택건수_카드론_EM_B0M       int64
컨택건수_CA_EM_B0M        int64
컨택건수_리볼빙_EM_B0M       int64
컨택건수_이용유도_EM_B0M      int64
컨택건수_카드론_청구서_B0M      int64
컨택건수_CA_청구서_B0M       int64
컨택건수_리볼빙_청구서_B0M      int64
컨택건수_이용유도_청구서_B0M     int64
컨택건수_카드론_인터넷_B0M      int64
컨택건수_CA_인터넷_B0M       int64
컨택건수_리볼빙_인터넷_B0M      int64
컨택건수_이용유도_인터넷_B0M     int64
컨택건수_카드론_당사앱_B0M      int64
컨택건수_CA_당사앱_B0M       int64
컨택건수_리볼빙_당사앱_B0M      int64
컨택건수_이용유도_당사앱_B0M     int64
컨택건수_카드론_TM_R6M       int64
컨택건수_CA_TM_R6M        int64
컨택건수_리볼빙_TM_R6M       int64
컨택건수_이용유도_TM_R6M      int64
컨택건수_신용발급_TM_R6M      int64
컨택건수_부대서비스_TM_R6M     int64
컨택건수_포인트소진_TM_R6M     int64
컨택건수_보험_TM_R6M        int64
컨택건수_카드론_LMS_R6M      int64
컨택건수_CA_LMS_R6M       int64
컨택건수_리볼빙_LMS_R6M      int64
컨택건수_이용유도_LMS_R6M     int64
컨택건수_카드론_EM_R6M       int64
컨택건수_CA_EM_R6M        int64
컨택건수_리볼빙_EM_R6M       int64
컨택건수_이용유도_EM_R6M      int64
컨택건수_카드론_청구서_R6M      int64
컨택건수_CA_청구서_R6M       int64
컨택건수_리볼빙_청구서_R6M      int64
컨택건수_이용유도_청구서_R6M     int64
컨택건수_카드론_인터넷_R6M      int64
컨택건수_CA_인터넷_R6M       int64
컨택건수_리볼빙_인터넷_R6M      int64
컨택건수_이용유도_인터넷_R6M     int64
컨택건수_카드론_당사앱_R6M      int64
컨택건수_CA_당사앱_R6M       int64
컨택건수_리볼빙_당사앱_R6M      int64
컨택건수_이용유도_당사앱_R6M     int64
컨택건수_채권_B0M           int64
컨택건수_FDS_B0M          int64
컨택건수_채권_R6M           int64
컨택건수_FDS_R6M          int64
캠페인접촉건수_R12M         object
캠페인접촉일수_R12M         object
dtype: object

## 결측치

In [ ]:
# 결측치 확인
merged_df.isna().sum()

ID                   0
Segment              0
기준년월                 0
컨택건수_카드론_TM_B0M      0
컨택건수_리볼빙_TM_B0M      0
컨택건수_CA_TM_B0M       0
컨택건수_이용유도_TM_B0M     0
컨택건수_신용발급_TM_B0M     0
컨택건수_부대서비스_TM_B0M    0
컨택건수_포인트소진_TM_B0M    0
컨택건수_보험_TM_B0M       0
컨택건수_카드론_LMS_B0M     0
컨택건수_CA_LMS_B0M      0
컨택건수_리볼빙_LMS_B0M     0
컨택건수_이용유도_LMS_B0M    0
컨택건수_카드론_EM_B0M      0
컨택건수_CA_EM_B0M       0
컨택건수_리볼빙_EM_B0M      0
컨택건수_이용유도_EM_B0M     0
컨택건수_카드론_청구서_B0M     0
컨택건수_CA_청구서_B0M      0
컨택건수_리볼빙_청구서_B0M     0
컨택건수_이용유도_청구서_B0M    0
컨택건수_카드론_인터넷_B0M     0
컨택건수_CA_인터넷_B0M      0
컨택건수_리볼빙_인터넷_B0M     0
컨택건수_이용유도_인터넷_B0M    0
컨택건수_카드론_당사앱_B0M     0
컨택건수_CA_당사앱_B0M      0
컨택건수_리볼빙_당사앱_B0M     0
컨택건수_이용유도_당사앱_B0M    0
컨택건수_카드론_TM_R6M      0
컨택건수_CA_TM_R6M       0
컨택건수_리볼빙_TM_R6M      0
컨택건수_이용유도_TM_R6M     0
컨택건수_신용발급_TM_R6M     0
컨택건수_부대서비스_TM_R6M    0
컨택건수_포인트소진_TM_R6M    0
컨택건수_보험_TM_R6M       0
컨택건수_카드론_LMS_R6M     0
컨택건수_CA_LMS_R6M      0
컨택건수_리볼빙_LMS_R6M     0
컨택건수_이용유도_LMS_R6M    0
컨택건수_카드론_EM_R6M      0
컨택건수_CA_EM_R6M       0
컨택건수_리볼빙_EM_R6M      0
컨택건수_이용유도_EM_R6M     0
컨택건수_카드론_청구서_R6M     0
컨택건수_CA_청구서_R6M      0
컨택건수_리볼빙_청구서_R6M     0
컨택건수_이용유도_청구서_R6M    0
컨택건수_카드론_인터넷_R6M     0
컨택건수_CA_인터넷_R6M      0
컨택건수_리볼빙_인터넷_R6M     0
컨택건수_이용유도_인터넷_R6M    0
컨택건수_카드론_당사앱_R6M     0
컨택건수_CA_당사앱_R6M      0
컨택건수_리볼빙_당사앱_R6M     0
컨택건수_이용유도_당사앱_R6M    0
컨택건수_채권_B0M          0
컨택건수_FDS_B0M         0
컨택건수_채권_R6M          0
컨택건수_FDS_R6M         0
캠페인접촉건수_R12M         0
캠페인접촉일수_R12M         0
dtype: int64

In [ ]:
# 이상치 확인
merged_df['캠페인접촉일수_R12M'].unique()

array(['1일 이상', '10일 이상', '15일 이상', '5일 이상', '20일 이상'], dtype=object)